import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const pageNum = Math.floor(Math.random() * 6)
const fetchU = `https://api.scryfall.com/cards/search?format=json&include_extras=false&include_multilingual=false&order=cmc&page=${pageNum}&q=c%3Ared+pow%3D3&unique=cards`
console.log(fetchU)

React.useEffect(() => {
    fetch(fetchU)
    .then(response => response.json())
    .then(data => {
        const rand = Math.floor(Math.random() * 175);
        console.log(data.data[rand].name)
        console.log(pageNum)
        });
}, [])

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Pick a Card
        </h1>
        <button>Random Card</button>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
